# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JVfdVtDnPh1HG7YNAT7WSWhzly4XsJvb
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns  #Visualization library to create more advance visualizations

df = pd.read_csv("churn.csv")

df.describe()

sns.set_style(style = "whitegrid")
plt.figure(figsize=(12,10))

# Plot the distribution between data to understand
sns.countplot(x="Exited", data=df)
plt.title("Distribution of Churn")
# Show imbalance to consider -> use technique oversampling or undersampling

# Plot age distribution
sns.histplot(data=df, x="Age", kde = True) #kde: kernel density estimate
plt.title("Age Distribution")

# Scatter plot of the customers vs age
sns.scatterplot(data=df, x="CreditScore", y="Age", hue="Exited")
plt.title("Credit Score vs Age")

# Box plot of account balance vs people who churn and didn't churn
sns.boxplot(x="Exited", y="Balance", data=df)
plt.title("Account Balance vs Churn")
# -> People who churn has higher account balance

# Box plot comparing credit score vs churn
# x,y is the column on dataset
sns.boxplot(x="Exited", y="CreditScore", data=df)
plt.title("Credit score vs churn")

# Takes only 1-2 arguments
features = df.drop(["RowNumber", "Surname", "CustomerId"], axis=1)  #exclude the exit column

# Feature engineering
features["CLV"] = df["Balance"] * df["EstimatedSalary"] / 100000      #Customer lifetime value categorizing into groups
features["AgeGroup"] = pd.cut(df["Age"], bins=[0,30,45,60,100], labels=["Young", "MiddleAged", "Senior", "Elderly"])
features["BalanceLevel"] = pd.cut(df["Balance"], bins=[-1, 50000, 150000, df["Balance"].max()], labels=["Low", "Medium", "High"])
features["CreditScoreRange"] = pd.cut(df["CreditScore"], bins=[0,580,670,740,850], labels=["Poor", "Fair", "Good", "Excellent"])
features["TenureGroup"] = pd.cut(df["Tenure"], bins=[-1, 3, 6, 10], labels=["New", "Midterm", "Longterm"])
features["ProductCategory"] = pd.cut(df["NumOfProducts"], bins=[0, 1, 2, df["NumOfProducts"].max()], labels=["Single", "Double", "Multiple"])

features["BalanceRatio"] = df["Balance"] / df["EstimatedSalary"]
features["CreditScoreRatio"] = df["CreditScore"] / df["EstimatedSalary"]
features["CreditScoreToAgeRatio"] = df["CreditScore"] / df["Age"]
features["TenureAgeRatio"] = df["Tenure"] / df["Age"]
features["AvgTenurePerProduct"] = df["Tenure"] / df["NumOfProducts"]
features["SalaryToCreditScoreRatio"] = df["EstimatedSalary"] / df["CreditScore"]
features["SalaryToAgeRatio"] = df["EstimatedSalary"] / df["Age"]
features["IsZeroBalance"] = (df["Balance"] == 0).astype(int)
features["AgeBalanceInteraction"] = df["Age"] * df["Balance"]
features["ActiveTenureRatio"] = df["IsActiveMember"] * df["Tenure"] / df["Age"]
features["TenureWeight"] = 1 / (1 + df["Tenure"])

features

import numpy as np

# Replace inf with nan value
# features.replace([np.inf, -np.inf], np.nan, inplace=True)

# Drop rows that has missing values
features = features.dropna()

features

target = features["Exited"]

target.shape

# Takes only 1-2 arguments
features = features.drop(["Exited"], axis=1)  #exclude the exit column

features

# convert the variables to numerical format using one hot encoding (binary format) because ML requires numerical inputs
features = pd.get_dummies(features, columns=["AgeGroup", "CreditScoreRange", "TenureGroup", "BalanceLevel", "Gender", "Geography", "ProductCategory"])

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler

features

X_train, X_test, Y_train, Y_test = train_test_split(features, target, test_size=0.2, random_state=42)

print(type(X_train), type(X_test), type(Y_train), type(Y_test))

from sklearn.ensemble import RandomForestClassifier

# Train a Random Forest to get feature importances
rf_classifier = RandomForestClassifier(n_estimators=200, random_state=1)
rf_classifier.fit(X_train, Y_train)
feature_importances = rf_classifier.feature_importances_
feature_names = features.columns

feature_importances_df = pd.DataFrame({
    "feature": feature_names,
    "importance": feature_importances
})

# Sort the most importance features from high to low
feature_importances_df = feature_importances_df.sort_values("importance", ascending=False)

# Get top 21 features based on importance
top_features = feature_importances_df["feature"][:21]

# Keep only the top 21 features in the features DataFrame
features = features[top_features]

X_new_train, X_new_test, Y_new_train, Y_new_test = train_test_split(features, target, test_size=0.2, random_state=42)

# Scale the features because some numbers are very large -> skew the model -> normalize the range -> reduce bias
scaler = MinMaxScaler()

X_new_train = scaler.fit_transform(X_new_train)
X_new_test = scaler.fit_transform(X_new_test)

print(type(X_train), type(X_test), type(Y_train), type(Y_test))

X_train[1]

# Logic regression model
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pickle

import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

lr_model = LogisticRegression(random_state=42)
lr_model.fit(X_train, Y_train)

lr_predictions = lr_model.predict(X_test)

lr_accuracy = accuracy_score(Y_test, lr_predictions)
lr_accuracy

def evaluate_and_save_model(model, X_train, X_test, Y_train, Y_test, filename):
  model.fit(X_train, Y_train)
  y_pred = model.predict(X_test)
  accuracy = accuracy_score(Y_test, y_pred)
  print(f"Accuracy: {accuracy:.4f}")
  print(f"Classification Report: \n{classification_report(Y_test, y_pred)}")
  print("-----------------")

  with open(filename, "wb") as file:
    pickle.dump(model, file)

  print(f"Model saved as {filename}")

xgb_model = xgb.XGBClassifier(random_state=42)
evaluate_and_save_model(xgb_model, X_train, X_test, Y_train, Y_test, "xgb_model.pkl")

dt_model = DecisionTreeClassifier(random_state=42)
evaluate_and_save_model(dt_model, X_train, X_test, Y_train, Y_test, "dt_model.pkl")

rf_model = RandomForestClassifier(random_state=42)
evaluate_and_save_model(rf_model, X_train, X_test, Y_train, Y_test, "rf_model.pkl")

gb_model = GaussianNB()
evaluate_and_save_model(gb_model, X_train, X_test, Y_train, Y_test, "gb_model.pkl")

knn_model = KNeighborsClassifier()
evaluate_and_save_model(knn_model, X_train, X_test, Y_train, Y_test, "knn_model.pkl")

svm_model = SVC(random_state=42)
evaluate_and_save_model(svm_model, X_train, X_test, Y_train, Y_test, "svm_model.pkl")

"""1. Precision: 80% means 80/100 customers churn

2. Recall: 90% means the model correctly predicted 90/100 churners who are likely to leave.

--> We want to maximize the recall so that we can keep the most customers that are likely to churn --> Prioritize looking at the recall statistics.
"""

# Rank the features
feature_importances = rf_model.feature_importances_
feature_names = features.columns

from sklearn.ensemble import RandomForestClassifier

# Train a Random Forest to get feature importances
rf_classifier = RandomForestClassifier(n_estimators=200, random_state=1)
rf_classifier.fit(X_train, Y_train)
feature_importances = rf_classifier.feature_importances_
feature_names = features.columns

feature_importances

feature_importances_df = pd.DataFrame({
    "feature": feature_names,
    "importance": feature_importances
})

feature_importances_df

# Sort the most importance features from high to low
feature_importances_df = feature_importances_df.sort_values("importance", ascending=False)

feature_importances_df

# Get top 21 features based on importance
top_features = feature_importances_df["feature"][:21]

# Keep only the top 21 features in the features DataFrame
features = features[top_features]

features

plt.figure(figsize=(10,6))
plt.bar(feature_importances_df["feature"], feature_importances_df["importance"])
plt.xticks(rotation=90)
plt.xlabel("Features")
plt.ylabel("Importance")
plt.title("Feature Importance")
plt.tight_layout()
plt.show()

"""Improve model accuracy:
1. Feature Engineering: extract more features from the raw data
2. SMOTE (Synthetic minority oversampling technique): creating new synthetic data for the minority class in the dataset -> balance the dataset
3. Ensembling: combining of multiple machine learning models together to create a new model
"""

X_new_train, X_new_test, Y_new_train, Y_new_test = train_test_split(features, target, test_size=0.2, random_state=42)

X_new_train.shape

print(type(X_new_train), type(X_new_test), type(Y_new_train), type(Y_new_test))

# Scale the features because some numbers are very large -> skew the model -> normalize the range -> reduce bias
X_new_train = scaler.fit_transform(X_new_train)
X_new_test = scaler.fit_transform(X_new_test)

print(type(X_new_train), type(X_new_test), type(Y_new_train), type(Y_new_test))

xgboost_model = xgb.XGBClassifier(random_state=42)
evaluate_and_save_model(xgboost_model, X_train, X_test, Y_train, Y_test, "xgboost_featureEngineermodel.pkl")

# xgb_new_model = xgb.XGBClassifier(random_state=42)
# evaluate_and_save_model(xgb_new_model, X_new_train, X_new_test, Y_new_train, Y_new_test, "xgb_new_model.pkl")

# dt_new_model = DecisionTreeClassifier(random_state=42)
# evaluate_and_save_model(dt_new_model, X_new_train, X_new_test, Y_new_train, Y_new_test, "dt_new_model.pkl")

rf_new_model = RandomForestClassifier(random_state=42)
evaluate_and_save_model(rf_new_model, X_new_train, X_new_test, Y_new_train, Y_new_test, "rf_new_model.pkl")

# gb_new_model = GaussianNB()
# evaluate_and_save_model(gb_new_model, X_new_train, X_new_test, Y_new_train, Y_new_test, "gb_new_model.pkl")

# knn_new_model = KNeighborsClassifier()
# evaluate_and_save_model(knn_new_model, X_new_train, X_new_test, Y_new_train, Y_new_test, "knn_new_model.pkl")

# svm_new_model = SVC(random_state=42)
# evaluate_and_save_model(svm_new_model, X_new_train, X_new_test, Y_new_train, Y_new_test, "svm_new_model.pkl")

# from imblearn.over_sampling import SMOTE

# smote = SMOTE(random_state=42)
# X_resampled, Y_resampled = smote.fit_resample(X_train, Y_train)
# evaluate_and_save_model(xgb_new_model, X_resampled, X_new_test, Y_resampled, Y_new_test, "xgboost_SMOTE.pkl")
# evaluate_and_save_model(dt_new_model, X_resampled, X_new_test, Y_resampled, Y_new_test, "dt_new_model.pkl")
# evaluate_and_save_model(rf_new_model, X_resampled, X_test, Y_resampled, Y_test, "rf_new_model.pkl")
# evaluate_and_save_model(gb_new_model, X_resampled, X_new_test, Y_resampled, Y_new_test, "gb_new_model.pkl")
# evaluate_and_save_model(knn_new_model, X_resampled, X_new_test, Y_resampled, Y_new_test, "knn_new_model.pkl")
# evaluate_and_save_model(svm_new_model, X_resampled, X_new_test, Y_resampled, Y_new_test, "svm_new_model.pkl")

from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=42)
X_resampled, Y_resampled = ros.fit_resample(X_train, Y_train)
evaluate_and_save_model(rf_new_model, X_resampled, X_test, Y_resampled, Y_test, "rf_new_model.pkl")

from sklearn.ensemble import VotingClassifier

voting_clf = VotingClassifier(
    estimators=[('xgb', xgb.XGBClassifier(random_state=42)),
     ("rf", RandomForestClassifier(random_state=42)),
      ("svm", SVC(probability=True, random_state=42))],
    voting="soft"
)
# soft: the voting classifier will weight the predictions of the individual models by their accuracy
# hard: the voting classifier will simply take the majority vote of the individual models.

evaluate_and_save_model(voting_clf, X_new_train, X_new_test, Y_new_train, Y_new_test, "voting_classifier.pkl")

evaluate_and_save_model(voting_clf1, X_train, X_test, Y_train, Y_test, "voting_classifier1.pkl")

# Focus on recall, improve accuracy

voting_clf1 = VotingClassifier(
    estimators=[("rf", RandomForestClassifier(random_state=42)),
                ("xgb", xgb.XGBClassifier(random_state=42)),
                ("gb", GaussianNB()),
                ("knn", KNeighborsClassifier()),
      ("svm", SVC(probability=True, random_state=42))],
    voting="soft"
)
# soft: the voting classifier will weight the predictions of the individual models by their accuracy
# hard: the voting classifier will simply take the majority vote of the individual models.

evaluate_and_save_model(voting_clf1, X_new_train, X_new_test, Y_new_train, Y_new_test, "voting_classifier1.pkl")
